"""Ministry

Revision ID: 950bd300431c
Revises: 1b02110e28ee
Create Date: 2024-06-03 15:13:58.811485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950bd300431c'
down_revision = '1b02110e28ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ministries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ministries')
    # ### end Alembic commands ###
